### ISSUE TITLE
Monitor subfolders

### ISSUE THREAD

**Issue by HeikoAdams** [pulb/mailnag-goa-plugin#1]
Since there aren't any options to configure the monitored folders any folder should be monitored for new mails.

**Comment by pulb** [comment]
I've just tried to fetch all mailbox names from my IMAP acounts. 
For Gmail I get the following reply:

```
(\HasNoChildren) "/" "INBOX"
(\HasNoChildren) "/" "Personal"
(\HasNoChildren) "/" "Receipts"
(\HasNoChildren) "/" "Travel"
(\HasNoChildren) "/" "Work"
(\HasChildren \Noselect) "/" "[Google Mail]"
(\All \HasNoChildren) "/" "[Google Mail]/All Mail"
(\Drafts \HasNoChildren) "/" "[Google Mail]/Drafts"
(\HasNoChildren \Important) "/" "[Google Mail]/Important"
(\HasNoChildren \Sent) "/" "[Google Mail]/Sent Mail"
(\Junk \HasNoChildren) "/" "[Google Mail]/Spam"
(\Flagged \HasNoChildren) "/" "[Google Mail]/Starred"
(\HasNoChildren \Trash) "/" "[Google Mail]/Trash"
(\HasChildren) "/" "test"
(\HasNoChildren) "/" "test/test2"
```

For GMX it looks like this:

```
(\Drafts \NoInferiors) "/" Entw&APw-rfe
(\Trash \HasNoChildren) "/" Gel&APY-scht
(\Sent \NoInferiors) "/" Gesendet
(\HasNoChildren) "/" INBOX
(\NoInferiors) "/" OUTBOX
(\HasNoChildren) "/" Papierkorb
(\HasNoChildren) "/" Sent
(\Junk \NoInferiors) "/" Spamverdacht
(\HasNoChildren) "/" Trash
```

Not quite sure how to identify the relevant mailboxes...

**Comment by pulb** [comment]
According to the [IMAP LIST Extension RFC](https://tools.ietf.org/html/rfc6154), mail servers are free to implement attributes like \Trash \Sent \All etc. So it seems there's no clean way to determine mailboxes for incoming mail. In addition, some mailboxes may also be virtual mailboxes linking to or combining other mailboxes.

For now I think it's best to leave the GOA plugin as simple as it is. Advanced users can still use Mailnag's built-in account configuration if they need to fine tune settings like IMAP folders.

**Comment by HeikoAdams** [comment]
Would it instead be possible to monitor the inbox and its subfolders?
