### ISSUE TITLE
mailnag-goa-plugin does not show up in mailnag-config

### ISSUE THREAD

**Issue by breakingflower** [pulb/mailnag-goa-plugin#5]
OS: Ubuntu 20.04

Installed using instructions, i.e. 

```
sudo add-apt-repository ppa:pulb/mailnag
sudo apt-get update
sudo apt-get install mailnag-goa-plugin
```

Dependency versions

```
gnome-online-accounts: 3.36.0-1ubuntu1
gir1.2-goa-1.0: 3.36.0-1ubuntu1
mailnag-goa-plugin: 2.0.0-0~ubuntu20.04.1
```

The plugin does not show up in the "plugins" tab of mailnag-config. The accounts of "online accounts" don't show up either.

**Comment by pulb** [comment]
Thanks for reporting, there was a bug in the packaging files.
Please `sudo apt upgrade` to install the update and let me know if it works for you.

**Comment by breakingflower** [comment]
The plugin shows, but accounts accessible in "Online Accounts" are not visible under "Accounts".

**Comment by pulb** [comment]
Yes, that's normal, it pulls account infos from Goa on every restart and does not copy them.
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by breakingflower** [comment]
Testing. Will report with new issue if it does not work as intended.
